name: C/C++ CI

on: [push, pull_request]

jobs:
  build-linux:
  name: Linux build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: CMake configure
      run: |
        cmake .
    - name: build
      run: |
        cmake --build .

  build-windows:
    name: Windows build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake configure
      run: |
        cmake -G "Visual Studio 16 2019" .
    - name: Build (MSVC)
      run: |
        cmake --build .
